name: Release Workflow
'on':
  workflow_dispatch: {}
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  schedule:
  - cron: 0 6 * * 2
  push:
    branches:
    - main
permissions:
  contents: write
run-name: Release Workflow
defaults:
  run:
    shell: bash
jobs:
  health_check_matrix:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python-version:
        - '3.12'
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      id: checkout_repository
      uses: actions/checkout@main
    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Poetry
      id: setup_poetry
      uses: snok/install-poetry@main
    - name: Add Poetry To Windows Path
      id: add_poetry_to_windows_path
      run: echo 'C:/Users/runneradmin/.local/bin' >> $GITHUB_PATH
      if: ${{ runner.os }} == 'Windows'
    - name: Pre Install Pygame From Binary
      id: pre_install_pygame_from_binary
      run: 'pip install pygame --only-binary=:all:'
    - name: Install Python Dependencies
      id: install_python_dependencies
      run: poetry install --with dev
    - name: Update Dependencies
      id: update_dependencies
      run: poetry update --with dev
    - name: Add Dependency Updates To Git
      id: add_dependency_updates_to_git
      run: git add pyproject.toml poetry.lock
    - name: Setup Keyring
      id: setup_keyring
      run: poetry run pip install keyrings.alt && poetry run python -c "import keyring;
        from keyrings.alt.file import PlaintextKeyring; keyring.set_keyring(PlaintextKeyring());"
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: Protect Repository
      id: protect_repository
      run: poetry run winipedia-utils protect-repo
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: Run Pre Commit Hooks
      id: run_pre_commit_hooks
      run: poetry run pre-commit run --all-files
    - name: Run Tests
      id: run_tests
      run: poetry run pytest --log-cli-level=INFO
  health_check:
    needs:
    - health_check_matrix
    runs-on: ubuntu-latest
    steps:
    - name: Aggregate Matrix Results
      id: aggregate_matrix_results
      run: echo 'Aggregating matrix results into one job.'
  build:
    needs:
    - health_check
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: No Build Script
      id: no_build_script
      run: echo 'No build script found. Skipping build.'
  release:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      id: checkout_repository
      uses: actions/checkout@main
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@main
      with:
        python-version: '3.12'
    - name: Setup Poetry
      id: setup_poetry
      uses: snok/install-poetry@main
    - name: Pre Install Pygame From Binary
      id: pre_install_pygame_from_binary
      run: 'pip install pygame --only-binary=:all:'
    - name: Install Python Dependencies
      id: install_python_dependencies
      run: poetry install --with dev
    - name: Update Dependencies
      id: update_dependencies
      run: poetry update --with dev
    - name: Add Dependency Updates To Git
      id: add_dependency_updates_to_git
      run: git add pyproject.toml poetry.lock
    - name: Setup Keyring
      id: setup_keyring
      run: poetry run pip install keyrings.alt && poetry run python -c "import keyring;
        from keyrings.alt.file import PlaintextKeyring; keyring.set_keyring(PlaintextKeyring());"
    - name: Setup Git
      id: setup_git
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
        && git config --global user.name "github-actions[bot]"
    - name: Add Version Patch
      id: add_version_patch
      run: poetry version patch && git add pyproject.toml
    - name: Run Pre Commit Hooks
      id: run_pre_commit_hooks
      run: poetry run pre-commit run --all-files
    - name: Commit Added Changes
      id: commit_added_changes
      run: 'git commit --no-verify -m ''[skip ci] CI/CD: Committing possible added
        changes (e.g.: pyproject.toml and poetry.lock)'''
    - name: Push Commits
      id: push_commits
      run: git push
    - name: Create And Push Tag
      id: create_and_push_tag
      run: git tag v$(poetry version -s) && git push origin v$(poetry version -s)
    - name: Extract Version
      id: extract_version
      run: echo "version=v$(poetry version -s)" >> $GITHUB_OUTPUT
    - name: Download Artifacts
      id: download_artifacts
      uses: actions/download-artifact@main
      with:
        path: artifacts
        merge-multiple: 'true'
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@develop
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@main
      with:
        tag: ${{ steps.extract_version.outputs.version }}
        name: ${{ github.event.repository.name }} ${{ steps.extract_version.outputs.version
          }}
        body: ${{ steps.build_changelog.outputs.changelog }}
        artifacts: artifacts/*
